
//! Autogenerated weights for `pallet_travel_points`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-02-07, STEPS: `50`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chery`, CPU: `13th Gen Intel(R) Core(TM) i7-1360P`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_travel_points
// --extrinsic=*
// --steps=50
// --repeat=200
// --wasm-execution=compiled
// --output=pallets/travel-points/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_travel_points`.
pub trait WeightInfo {
	fn award_points() -> Weight;
	fn spend_points() -> Weight;
	fn cleanup_expired() -> Weight;
	fn authorize_issuer() -> Weight;
	fn revoke_issuer() -> Weight;
	fn set_admin() -> Weight;
	fn mint_ticket() -> Weight;
	fn redeem_ticket() -> Weight;
	fn transfer_ticket() -> Weight;
	fn unmint_ticket() -> Weight;
	fn force_unmint_ticket() -> Weight;
	fn cleanup_expired_tickets() -> Weight;
	fn stake() -> Weight;
	fn unstake() -> Weight;
	fn add_to_reward_pool() -> Weight;
	fn request_unbond() -> Weight;
	fn withdraw_unbonded() -> Weight;
	fn cancel_unbonding() -> Weight;
	fn slash_staker() -> Weight;
	fn create_pool() -> Weight;
	fn delegate() -> Weight;
	fn undelegate() -> Weight;
	fn set_pool_commission() -> Weight;
	fn close_pool() -> Weight;
	fn rotate_era() -> Weight;
	fn distribute_rewards() -> Weight;
	fn claim_rewards() -> Weight;
	fn increase_stake() -> Weight;
}

/// Weights for `pallet_travel_points` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn award_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `6015`
		// Minimum execution time: 15_058_000 picoseconds.
		Weight::from_parts(15_665_000, 6015)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn spend_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 23_805_000 picoseconds.
		Weight::from_parts(24_556_000, 6015)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn cleanup_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6015`
		// Minimum execution time: 14_974_000 picoseconds.
		Weight::from_parts(15_613_000, 6015)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn authorize_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `3514`
		// Minimum execution time: 11_108_000 picoseconds.
		Weight::from_parts(11_561_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn revoke_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `132`
		//  Estimated: `3514`
		// Minimum execution time: 12_399_000 picoseconds.
		Weight::from_parts(13_018_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:1)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `1517`
		// Minimum execution time: 8_745_000 picoseconds.
		Weight::from_parts(9_111_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::NextTicketId` (r:1 w:1)
	/// Proof: `TravelPoints::NextTicketId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:0 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn mint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 33_049_000 picoseconds.
		Weight::from_parts(34_201_000, 6015)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn redeem_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `4644`
		// Minimum execution time: 11_846_000 picoseconds.
		Weight::from_parts(12_582_000, 4644)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:2 w:2)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn transfer_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `9240`
		// Minimum execution time: 18_786_000 picoseconds.
		Weight::from_parts(19_650_000, 9240)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn unmint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `5115`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_500_000, 5115)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn force_unmint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `5115`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_500_000, 5115)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:50 w:50)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn cleanup_expired_tickets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `182700`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(25_000_000, 182700)
			.saturating_add(T::DbWeight::get().reads(51_u64))
			.saturating_add(T::DbWeight::get().writes(51_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `33487`
		// Minimum execution time: 12_011_000 picoseconds.
		Weight::from_parts(12_560_000, 33487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `33487`
		// Minimum execution time: 15_302_000 picoseconds.
		Weight::from_parts(15_970_000, 33487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::RewardPool` (r:1 w:1)
	/// Proof: `TravelPoints::RewardPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn add_to_reward_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1501`
		// Minimum execution time: 4_363_000 picoseconds.
		Weight::from_parts(4_635_000, 1501)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UnbondingRequests` (r:1 w:1)
	/// Proof: `TravelPoints::UnbondingRequests` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn request_unbond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `4282`
		// Minimum execution time: 17_020_000 picoseconds.
		Weight::from_parts(17_506_000, 4282)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::UnbondingRequests` (r:1 w:1)
	/// Proof: `TravelPoints::UnbondingRequests` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:0)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn withdraw_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `4282`
		// Minimum execution time: 14_371_000 picoseconds.
		Weight::from_parts(15_327_000, 4282)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::UnbondingRequests` (r:1 w:1)
	/// Proof: `TravelPoints::UnbondingRequests` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn cancel_unbonding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `4282`
		// Minimum execution time: 16_714_000 picoseconds.
		Weight::from_parts(17_327_000, 4282)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::SlashRecords` (r:1 w:1)
	/// Proof: `TravelPoints::SlashRecords` (`max_values`: None, `max_size`: Some(2150), added: 4625, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalSlashed` (r:1 w:1)
	/// Proof: `TravelPoints::TotalSlashed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn slash_staker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `222`
		//  Estimated: `5615`
		// Minimum execution time: 19_330_000 picoseconds.
		Weight::from_parts(20_115_000, 5615)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::NextPoolId` (r:1 w:1)
	/// Proof: `TravelPoints::NextPoolId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Pools` (r:0 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1501`
		// Minimum execution time: 9_918_000 picoseconds.
		Weight::from_parts(10_528_000, 1501)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Delegations` (r:1 w:1)
	/// Proof: `TravelPoints::Delegations` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PoolDelegators` (r:1 w:1)
	/// Proof: `TravelPoints::PoolDelegators` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `192`
		//  Estimated: `6687`
		// Minimum execution time: 19_144_000 picoseconds.
		Weight::from_parts(19_972_000, 6687)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::Delegations` (r:1 w:1)
	/// Proof: `TravelPoints::Delegations` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PoolDelegators` (r:1 w:1)
	/// Proof: `TravelPoints::PoolDelegators` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn undelegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `361`
		//  Estimated: `6687`
		// Minimum execution time: 21_019_000 picoseconds.
		Weight::from_parts(22_011_000, 6687)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	fn set_pool_commission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `3562`
		// Minimum execution time: 10_654_000 picoseconds.
		Weight::from_parts(11_047_000, 3562)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn close_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `192`
		//  Estimated: `3562`
		// Minimum execution time: 13_286_000 picoseconds.
		Weight::from_parts(14_014_000, 3562)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::LastEraBlock` (r:1 w:1)
	/// Proof: `TravelPoints::LastEraBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::CurrentEra` (r:1 w:1)
	/// Proof: `TravelPoints::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:0)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::EraVerifiers` (r:0 w:1)
	/// Proof: `TravelPoints::EraVerifiers` (`max_values`: None, `max_size`: Some(693), added: 3168, mode: `MaxEncodedLen`)
	fn rotate_era() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `33487`
		// Minimum execution time: 20_197_000 picoseconds.
		Weight::from_parts(20_995_000, 33487)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::RewardPool` (r:1 w:1)
	/// Proof: `TravelPoints::RewardPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:0)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:0)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:2 w:0)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PendingStakerRewards` (r:1 w:1)
	/// Proof: `TravelPoints::PendingStakerRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn distribute_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `6078`
		// Minimum execution time: 21_144_000 picoseconds.
		Weight::from_parts(21_865_000, 6078)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::PendingStakerRewards` (r:1 w:1)
	/// Proof: `TravelPoints::PendingStakerRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PendingIssuerRewards` (r:1 w:1)
	/// Proof: `TravelPoints::PendingIssuerRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `95`
		//  Estimated: `3529`
		// Minimum execution time: 14_237_000 picoseconds.
		Weight::from_parts(14_791_000, 3529)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn increase_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `3534`
		// Minimum execution time: 12_068_000 picoseconds.
		Weight::from_parts(12_728_000, 3534)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn award_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `6015`
		// Minimum execution time: 15_058_000 picoseconds.
		Weight::from_parts(15_665_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn spend_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 23_805_000 picoseconds.
		Weight::from_parts(24_556_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn cleanup_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6015`
		// Minimum execution time: 14_974_000 picoseconds.
		Weight::from_parts(15_613_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn authorize_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `3514`
		// Minimum execution time: 11_108_000 picoseconds.
		Weight::from_parts(11_561_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn revoke_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `132`
		//  Estimated: `3514`
		// Minimum execution time: 12_399_000 picoseconds.
		Weight::from_parts(13_018_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:1)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `1517`
		// Minimum execution time: 8_745_000 picoseconds.
		Weight::from_parts(9_111_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::NextTicketId` (r:1 w:1)
	/// Proof: `TravelPoints::NextTicketId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:0 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn mint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 33_049_000 picoseconds.
		Weight::from_parts(34_201_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn redeem_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `4644`
		// Minimum execution time: 11_846_000 picoseconds.
		Weight::from_parts(12_582_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:2 w:2)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn transfer_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `9240`
		// Minimum execution time: 18_786_000 picoseconds.
		Weight::from_parts(19_650_000, 9240)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn unmint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `5115`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_500_000, 5115)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn force_unmint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `5115`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_500_000, 5115)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:50 w:50)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn cleanup_expired_tickets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `182700`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(25_000_000, 182700)
			.saturating_add(RocksDbWeight::get().reads(51_u64))
			.saturating_add(RocksDbWeight::get().writes(51_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `33487`
		// Minimum execution time: 12_011_000 picoseconds.
		Weight::from_parts(12_560_000, 33487)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `33487`
		// Minimum execution time: 15_302_000 picoseconds.
		Weight::from_parts(15_970_000, 33487)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::RewardPool` (r:1 w:1)
	/// Proof: `TravelPoints::RewardPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn add_to_reward_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1501`
		// Minimum execution time: 4_363_000 picoseconds.
		Weight::from_parts(4_635_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UnbondingRequests` (r:1 w:1)
	/// Proof: `TravelPoints::UnbondingRequests` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn request_unbond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `4282`
		// Minimum execution time: 17_020_000 picoseconds.
		Weight::from_parts(17_506_000, 4282)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::UnbondingRequests` (r:1 w:1)
	/// Proof: `TravelPoints::UnbondingRequests` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:0)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn withdraw_unbonded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `266`
		//  Estimated: `4282`
		// Minimum execution time: 14_371_000 picoseconds.
		Weight::from_parts(15_327_000, 4282)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::UnbondingRequests` (r:1 w:1)
	/// Proof: `TravelPoints::UnbondingRequests` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn cancel_unbonding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `4282`
		// Minimum execution time: 16_714_000 picoseconds.
		Weight::from_parts(17_327_000, 4282)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::SlashRecords` (r:1 w:1)
	/// Proof: `TravelPoints::SlashRecords` (`max_values`: None, `max_size`: Some(2150), added: 4625, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalSlashed` (r:1 w:1)
	/// Proof: `TravelPoints::TotalSlashed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn slash_staker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `222`
		//  Estimated: `5615`
		// Minimum execution time: 19_330_000 picoseconds.
		Weight::from_parts(20_115_000, 5615)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::NextPoolId` (r:1 w:1)
	/// Proof: `TravelPoints::NextPoolId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Pools` (r:0 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1501`
		// Minimum execution time: 9_918_000 picoseconds.
		Weight::from_parts(10_528_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Delegations` (r:1 w:1)
	/// Proof: `TravelPoints::Delegations` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PoolDelegators` (r:1 w:1)
	/// Proof: `TravelPoints::PoolDelegators` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `192`
		//  Estimated: `6687`
		// Minimum execution time: 19_144_000 picoseconds.
		Weight::from_parts(19_972_000, 6687)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::Delegations` (r:1 w:1)
	/// Proof: `TravelPoints::Delegations` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PoolDelegators` (r:1 w:1)
	/// Proof: `TravelPoints::PoolDelegators` (`max_values`: None, `max_size`: Some(3222), added: 5697, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn undelegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `361`
		//  Estimated: `6687`
		// Minimum execution time: 21_019_000 picoseconds.
		Weight::from_parts(22_011_000, 6687)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	fn set_pool_commission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `190`
		//  Estimated: `3562`
		// Minimum execution time: 10_654_000 picoseconds.
		Weight::from_parts(11_047_000, 3562)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Pools` (r:1 w:1)
	/// Proof: `TravelPoints::Pools` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn close_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `192`
		//  Estimated: `3562`
		// Minimum execution time: 13_286_000 picoseconds.
		Weight::from_parts(14_014_000, 3562)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::LastEraBlock` (r:1 w:1)
	/// Proof: `TravelPoints::LastEraBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::CurrentEra` (r:1 w:1)
	/// Proof: `TravelPoints::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:0)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::EraVerifiers` (r:0 w:1)
	/// Proof: `TravelPoints::EraVerifiers` (`max_values`: None, `max_size`: Some(693), added: 3168, mode: `MaxEncodedLen`)
	fn rotate_era() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `33487`
		// Minimum execution time: 20_197_000 picoseconds.
		Weight::from_parts(20_995_000, 33487)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::RewardPool` (r:1 w:1)
	/// Proof: `TravelPoints::RewardPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:0)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:0)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Stakes` (r:2 w:0)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PendingStakerRewards` (r:1 w:1)
	/// Proof: `TravelPoints::PendingStakerRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn distribute_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `6078`
		// Minimum execution time: 21_144_000 picoseconds.
		Weight::from_parts(21_865_000, 6078)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::PendingStakerRewards` (r:1 w:1)
	/// Proof: `TravelPoints::PendingStakerRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PendingIssuerRewards` (r:1 w:1)
	/// Proof: `TravelPoints::PendingIssuerRewards` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `95`
		//  Estimated: `3529`
		// Minimum execution time: 14_237_000 picoseconds.
		Weight::from_parts(14_791_000, 3529)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn increase_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `170`
		//  Estimated: `3534`
		// Minimum execution time: 12_068_000 picoseconds.
		Weight::from_parts(12_728_000, 3534)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
