
//! Autogenerated weights for `pallet_travel_points`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-31, STEPS: `50`, REPEAT: `200`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chery`, CPU: `13th Gen Intel(R) Core(TM) i7-1360P`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_travel_points
// --extrinsic=*
// --steps=50
// --repeat=200
// --wasm-execution=compiled
// --output=pallets/travel-points/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_travel_points`.
pub trait WeightInfo {
	fn award_points() -> Weight;
	fn spend_points() -> Weight;
	fn cleanup_expired() -> Weight;
	fn authorize_issuer() -> Weight;
	fn revoke_issuer() -> Weight;
	fn set_admin() -> Weight;
	fn mint_ticket() -> Weight;
	fn redeem_ticket() -> Weight;
	fn transfer_ticket() -> Weight;
	fn stake() -> Weight;
	fn unstake() -> Weight;
	fn add_to_reward_pool() -> Weight;
}

/// Weights for `pallet_travel_points` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn award_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `6015`
		// Minimum execution time: 26_016_000 picoseconds.
		Weight::from_parts(27_339_000, 6015)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn spend_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 41_697_000 picoseconds.
		Weight::from_parts(43_000_000, 6015)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn cleanup_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6015`
		// Minimum execution time: 26_553_000 picoseconds.
		Weight::from_parts(27_522_000, 6015)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn authorize_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `3514`
		// Minimum execution time: 19_327_000 picoseconds.
		Weight::from_parts(20_206_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn revoke_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `132`
		//  Estimated: `3514`
		// Minimum execution time: 22_005_000 picoseconds.
		Weight::from_parts(22_913_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:1)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `1517`
		// Minimum execution time: 15_064_000 picoseconds.
		Weight::from_parts(15_739_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::NextTicketId` (r:1 w:1)
	/// Proof: `TravelPoints::NextTicketId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:0 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn mint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 58_378_000 picoseconds.
		Weight::from_parts(60_111_000, 6015)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn redeem_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `4644`
		// Minimum execution time: 20_795_000 picoseconds.
		Weight::from_parts(22_073_000, 4644)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:2 w:2)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn transfer_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `9240`
		// Minimum execution time: 33_522_000 picoseconds.
		Weight::from_parts(34_923_000, 9240)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `33487`
		// Minimum execution time: 21_285_000 picoseconds.
		Weight::from_parts(22_272_000, 33487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `33487`
		// Minimum execution time: 26_765_000 picoseconds.
		Weight::from_parts(28_044_000, 33487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::RewardPool` (r:1 w:1)
	/// Proof: `TravelPoints::RewardPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn add_to_reward_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1501`
		// Minimum execution time: 7_679_000 picoseconds.
		Weight::from_parts(8_208_000, 1501)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn award_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `6015`
		// Minimum execution time: 26_016_000 picoseconds.
		Weight::from_parts(27_339_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn spend_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 41_697_000 picoseconds.
		Weight::from_parts(43_000_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn cleanup_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `6015`
		// Minimum execution time: 26_553_000 picoseconds.
		Weight::from_parts(27_522_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn authorize_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `3514`
		// Minimum execution time: 19_327_000 picoseconds.
		Weight::from_parts(20_206_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:0)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:1)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn revoke_issuer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `132`
		//  Estimated: `3514`
		// Minimum execution time: 22_005_000 picoseconds.
		Weight::from_parts(22_913_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Admin` (r:1 w:1)
	/// Proof: `TravelPoints::Admin` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `61`
		//  Estimated: `1517`
		// Minimum execution time: 15_064_000 picoseconds.
		Weight::from_parts(15_739_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::AuthorizedIssuers` (r:1 w:0)
	/// Proof: `TravelPoints::AuthorizedIssuers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserPoints` (r:1 w:1)
	/// Proof: `TravelPoints::UserPoints` (`max_values`: None, `max_size`: Some(2550), added: 5025, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalPoints` (r:1 w:1)
	/// Proof: `TravelPoints::TotalPoints` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::IssuerDailyRecords` (r:1 w:1)
	/// Proof: `TravelPoints::IssuerDailyRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::PeriodTotalSpent` (r:1 w:1)
	/// Proof: `TravelPoints::PeriodTotalSpent` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::NextTicketId` (r:1 w:1)
	/// Proof: `TravelPoints::NextTicketId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:1 w:1)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::Tickets` (r:0 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn mint_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298`
		//  Estimated: `6015`
		// Minimum execution time: 58_378_000 picoseconds.
		Weight::from_parts(60_111_000, 6015)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	fn redeem_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359`
		//  Estimated: `4644`
		// Minimum execution time: 20_795_000 picoseconds.
		Weight::from_parts(22_073_000, 4644)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `TravelPoints::Tickets` (r:1 w:1)
	/// Proof: `TravelPoints::Tickets` (`max_values`: None, `max_size`: Some(1179), added: 3654, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::UserTickets` (r:2 w:2)
	/// Proof: `TravelPoints::UserTickets` (`max_values`: None, `max_size`: Some(1650), added: 4125, mode: `MaxEncodedLen`)
	fn transfer_ticket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `415`
		//  Estimated: `9240`
		// Minimum execution time: 33_522_000 picoseconds.
		Weight::from_parts(34_923_000, 9240)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `33487`
		// Minimum execution time: 21_285_000 picoseconds.
		Weight::from_parts(22_272_000, 33487)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::Stakes` (r:1 w:1)
	/// Proof: `TravelPoints::Stakes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::StakerList` (r:1 w:1)
	/// Proof: `TravelPoints::StakerList` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `TravelPoints::TotalStaked` (r:1 w:1)
	/// Proof: `TravelPoints::TotalStaked` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `33487`
		// Minimum execution time: 26_765_000 picoseconds.
		Weight::from_parts(28_044_000, 33487)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `TravelPoints::RewardPool` (r:1 w:1)
	/// Proof: `TravelPoints::RewardPool` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn add_to_reward_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1501`
		// Minimum execution time: 7_679_000 picoseconds.
		Weight::from_parts(8_208_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
